apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-image-updater.argoproj.io/silkapp.update-strategy:latest
  name: silkapp-nginx
  namespace: silkapp-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: silkapp-nginx
  template:
    metadata:
      labels:
        app: silkapp-nginx
    spec:
      containers:
      - name: silkapp-nginx
        image: iyadomry/silkapp:v3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: silkapp-nginx-service
  namespace: silkapp-ns
spec:
  type: LoadBalancer  # Changed from ClusterIP to LoadBalancer
  selector:
    app: silkapp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

