apiVersion: v1
kind: Namespace
metadata:
  name: silkapp-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silkapp-nginx
  namespace: silkapp-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: silkapp-nginx
  template:
    metadata:
      labels:
        app: silkapp-nginx
    spec:
      containers:
      - name: silkapp-nginx
        sed -i 's|image: iyadomry/silkapp:.*|image: iyadomry/silkapp:${{ github.event.inputs.image_version }}|' ./project-argocd/k8s/nginx.yaml
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: silkapp-nginx-service
  namespace: silkapp-ns
spec:
  type: ClusterIP
  selector:
    app: silkapp-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
