apiVersion: v1
kind: Namespace
metadata:
  name: myapp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
  namespace: myapp
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-nginx-service
  namespace: myapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7070
    protocol: TCP
  selector:
    app: hello-world
