apiVersion: v1
kind: Namespace
metadata:
  name: silkapp-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silkapp-nginx
  namespace: silkapp-ns
  labels:
    app: silkapp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: silkapp-app
  template:
    metadata:
      labels:
        app: silkapp-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: silkapp-nginx-service
  namespace: silkapp-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7070
    protocol: TCP
  selector:
    app: silkapp-app
