apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: silkapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Iyadomry/argocd.git'
    targetRevision: HEAD
    path: project-argocd/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: silkapp-ns
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resourcres are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false