name: Build and Push Docker image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'New TAG'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./project-argocd/silkapp
        file: ./project-argocd/silkapp/Dockerfile
        push: true
        tags: iyadomry/silkapp:${{ github.event.inputs.image_version }}  # Replace with your Docker Hub username/repository

  update-version:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update version in YAML
        run: |
          sed -i 's|image: iyadomry/silkapp:v9|image: iyadomry/silkapp:${{ github.event.inputs.new_version }}|' ./project-argocd/k8s/nginx.yaml
        shell: bash

      - name: Configure Git
        run: |
          git config user.name "iyadomry"
          git config user.email "iyad2fast@hotmail.com"

      - name: Commit and push if changed
        run: |
          git add ./project-argocd/k8s/nginx.yaml
          git commit -m "Update silkapp-nginx image to ${{ github.event.inputs.new_version }}" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}