name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Set your default branch here, it could be 'master' for some repositories

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./project-argocd/silkapp
        file: ./project-argocd/silkapp/Dockerfile
        push: true
        tags: iyadomry/silkapp:v4  # Replace with your Docker Hub username/repository
